# Prefix キーを Ctrl-b から Ctrl-a に変更
set -g prefix C-a
unbind C-b

# ペイン
# bind | split-window -h -c '#{pane_current_path}'    # Prefix + | でペインを垂直分割する
# bind - split-window -v -c '#{pane_current_path}'    # Prefix + - でペインを水平分割する

# prefix+\でペインを垂直分割する
bind \\ split-window -h

# prefix+-でペインを水平分割する
bind - split-window -v

# prefixを押したときに、押されていることがわかるようにwindow-status-current-formatを次のように変更します。
setw -g window-status-current-format '#[bg=colour2,fg=colour255]#{?client_prefix,#[bg=colour3],} #I #W '

# マウス操作を有効にする
set-option -g mouse on
